name: Single vs Multiple Trigger

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version à déployer"
        required: false
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Version: ${{ github.event.inputs.version }}"'
